START TRANSACTION;

-- Xóa các chi tiết dịch vụ liên quan
DELETE FROM CHI_TIET_SU_DUNG_DV WHERE MADATPHONG IN (
    SELECT MADATPHONG FROM DAT_PHONG WHERE TRANGTHAIDAT = 'DA HUY'
);

-- Xóa đơn đặt phòng
DELETE FROM DAT_PHONG WHERE TRANGTHAIDAT = 'DA HUY';

-- HIỂN THỊ DANH SÁCH PHÒNG CÒN LẠi

SELECT MADATPHONG, MAPHONG, MAKH, NGAYDAT, GIOBATDAU, GIOKETTHUC, TIENDATCOC, GHICHU, TRANGTHAIDAT
FROM DAT_PHONG

COMMIT;