SELECT
    dp.MADATPHONG,
    p.MAPHONG,
    p.LOAIPHONG,
    p.GIAPHONG,
    kh.TENKH,
    dp.NGAYDAT,
    TIMESTAMPDIFF(MINUTE, dp.GIOBATDAU, dp.GIOKETTHUC) / 60 * p.GIAPHONG AS TongTienHat,
    COALESCE(SUM(ctsd.SOLUONG * dvdk.DONGIA), 0) AS TongTienSuDungDichVu,
    (TIMESTAMPDIFF(MINUTE, dp.GIOBATDAU, dp.GIOKETTHUC) / 60 * p.GIAPHONG) + COALESCE(SUM(ctsd.SOLUONG * dvdk.DONGIA), 0) AS ThongTinThanhToan
FROM
    DAT_PHONG AS dp
JOIN
    PHONG AS p ON dp.MAPHONG = p.MAPHONG
JOIN
    KHACH_HANG AS kh ON dp.MAKH = kh.MAKH
LEFT JOIN
    CHI_TIET_SU_DUNG_DV AS ctsd ON dp.MADATPHONG = ctsd.MADATPHONG
LEFT JOIN
    DICH_VU_DI_KEM AS dvdk ON ctsd.MADV = dvdk.MADV
GROUP BY
    dp.MADATPHONG, p.MAPHONG, p.LOAIPHONG, p.GIAPHONG, kh.TENKH, dp.NGAYDAT;